### ISSUE TITLE
Mobile mode

### ISSUE THREAD

**Issue by ramenatorr** [reddit-habs/nhl-highlights#1]
Hey Simon, have you ever considered adding a mobile  version of the hockey highlights page to your web app? Something super simple just to make scrolling and selecting links a bit more user friendly on mobile. Otherwise, awesome work. I've been using this a lot over the last few seasons.

**Comment by sbstp** [comment]
Hey, I added a commit that should make the pages look better on mobile https://github.com/sbstp/nhl-highlights/commit/6a4bae6fccee340282f63bf7618164caa68013c4

**Comment by ramenatorr** [comment]
Looks a lot better on mobile now!
