### ISSUE TITLE
Games missing in schedule

### ISSUE THREAD

**Issue by ramenatorr** [reddit-habs/nhl-highlights#2]
Hey hey, just an FYI but I noticed that since 02/07 that not all the scheduled games are appearing in the list. Not sure if it's an issue on your end or the NHL API. Anyway, I'll be curious to see what the issue/fix was. Take care!

**Comment by sbstp** [comment]
Thanks for the tip. I'll check what's going on soon. Sorry been quite busy

**Comment by sbstp** [comment]
Thanks for the report. It was an issue with rescheduled games because of COVID!

**Comment by ramenatorr** [comment]
No problem, Simon!

I did think it had to do with the rescheduled games, but I couldn't see why
from looking at the response payload from the NHL stats API call you use.
I'm glad you were able to fix it though :)

Thanks,

Ramen B.

**Comment by sbstp** [comment]
It took me a while to figure out what the issue was. I use a little SQLite database to cache the links to the videos and not spam the API too much, but it turns out those rescheduled games re-use the same ID and the last time, so just needed to distinguish them by date as well.
